[colors.primary]
background = '#111318'
foreground = '#e2e2e9'

[colors.selection]
text = '#e2e2e9'
background = '#2b4678'

[colors.cursor]
text = '#111318'
cursor = '#aec6ff'

[colors.normal]
black   = '#111318'
red     = '#e54d45'
green   = '#6fd66e'
yellow  = '#dbd27b'
blue    = '#607ed0'
magenta = '#8e9dbf'
cyan    = '#aec6ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0615f'
green   = '#86e086'
yellow  = '#e8e197'
blue    = '#bad4ff'
magenta = '#537cae'
cyan    = '#6c75b4'
white   = '#ffffff'
