# Chawan config - Vim-style keybindings

[display]
# Enable sixel/kitty graphics protocol for inline images
image-mode = "auto"

[buffer]
# Default search engine (DuckDuckGo)
default-search = "https://duckduckgo.com/?q=$1"

[page]
# Navigation - vim style
'j' = 'scrollDown'
'k' = 'scrollUp'
'h' = 'scrollLeft'
'l' = 'scrollRight'

# Fast scrolling
'C-d' = 'halfPageDown'
'C-u' = 'halfPageUp'
'C-f' = 'pageDown'
'C-b' = 'pageUp'

# Jump to top/bottom
'gg' = 'cursorFirstLine'
'G' = 'cursorLastLine'

# Line navigation
'0' = 'cursorLineBegin'
'^' = 'cursorLineBegin'
'$' = 'cursorLineEnd'

# Search
'/' = 'searchForward'
'?' = 'searchBackward'
'n' = 'searchNext'
'N' = 'searchPrev'

# Links and navigation
'f' = 'click'
'F' = 'clickNewTab'
'o' = 'load'
'O' = 'loadNewTab'
't' = 'loadNewTab'

# History
'H' = 'pageBack'
'L' = 'pageForward'
'C-o' = 'pageBack'
'C-i' = 'pageForward'

# Tabs/Buffers
'gt' = 'nextBuffer'
'gT' = 'prevBuffer'
'J' = 'nextBuffer'
'K' = 'prevBuffer'
'd' = 'discardBuffer'
'u' = 'undoClose'

# Reload
'r' = 'reload'
'R' = 'reloadForce'

# Misc
'gi' = 'cursorFirstInput'
'yy' = 'copyURL'
'p' = 'paste'
'P' = 'pasteNewTab'

# Quit
'q' = 'quit'
'ZZ' = 'quit'
'ZQ' = 'quit'

# Help
'M-?' = 'help'

[line]
# Line editing - vim/emacs style
'C-h' = 'backspace'
'C-w' = 'deleteWord'
'C-u' = 'clearLine'
'C-a' = 'cursorBegin'
'C-e' = 'cursorEnd'
'C-b' = 'cursorPrev'
'C-f' = 'cursorNext'
'M-b' = 'cursorPrevWord'
'M-f' = 'cursorNextWord'
'C-k' = 'killLine'
'C-n' = 'nextHist'
'C-p' = 'prevHist'
